# -*- coding: utf-8 -*-
"""python0914

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16eYd2C1ymrkEilI7PqsW0Jz2_5oYXWlq
"""

import pandas as pd

df_1=pd.read_csv("csv1.csv")
df_2=pd.read_csv("csv2.csv")


student_names_1 = df_1['name']
student_names_2 = df_2['name']

student_names_1_set = set(student_names_1)
student_names_2_set = set(student_names_2)

print(student_names_1_set&student_names_2_set)
print(student_names_1_set|student_names_2_set)